"""Generate a synthetic campaign sales/engagement table correlated with real
Content Understanding commercial-video fields.

This implements the "Later: simulated data for marketing effectiveness" plan
described in `fabric/README.md`: a `campaign_sales_simulated` table of
impressions/clicks/conversions/revenue, one row per synthetic commercial
sample already generated by `generate_synthetic_commercials.py`, so it can be
joined to the `campaign_insights` Delta table on `campaign_name` + the result
`id` embedded in `file_path`.

This script does **not** represent real Progressive sales, media spend, or
performance data. Every number here is a seeded, deterministic simulation for
demo purposes only, and every row is marked `is_simulated = true`.

The simulation intentionally correlates engagement/conversion with real
Content Understanding output for the *same* video, so the demo can show a
believable (if invented) marketing-effectiveness story:

- Click-through rate is higher when the v2 schema's classified
  `SentimentCategory` (see `generate_synthetic_commercials_v2.py`) is
  "Positive" rather than "Mixed" (comedic discomfort/awkwardness), and higher
  again when the video references sports/entertainment (a proxy for broader
  cultural relevance).
- Conversion rate (clicks -> policy quotes) varies by the classified
  `CallToActionType`: a direct "GetAQuote"/"PhoneCall" ask converts better
  than a softer "VisitWebsite"/"PurchaseNow" ask, a common real-world
  marketing pattern reproduced here for demo realism.
- Shorter (15s) cuts are modeled as cheaper to air at the same budget, so
  they are simulated with proportionally higher impression counts than
  30s spots.

Usage:
    python fabric/sample-data/generate_synthetic_sales.py

Writes `fabric/sample-data/campaign-sales/campaign_sales_simulated.csv` by
default. Copy that file alongside the `cu-results` OneLake shortcut (or into
its own shortcut/table) and load it in a Fabric notebook to join with
`campaign_insights` -- see fabric/README.md for the walkthrough.
"""

from __future__ import annotations

import argparse
import csv
import random
from pathlib import Path

from generate_synthetic_commercials import CAMPAIGNS, _stable_id  # noqa: E402  (sibling-script import)
from generate_synthetic_commercials_v2 import (  # noqa: E402  (sibling-script import)
    _classify_call_to_action_type,
    _classify_sentiment_category,
)

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_OUTPUT_PATH = SCRIPT_DIR / "campaign-sales" / "campaign_sales_simulated.csv"

FIELDNAMES = [
    "campaign_name",
    "result_id",
    "duration_ms",
    "impressions",
    "clicks",
    "click_through_rate",
    "conversions",
    "conversion_rate",
    "revenue_usd",
    "sentiment_category",
    "call_to_action_type",
    "is_simulated",
]


def _simulate_row(rng: random.Random, campaign_name: str, variant_index: int, variant: dict) -> dict:
    result_id = _stable_id(campaign_name, variant_index)
    duration_ms = variant["duration_ms"]
    sentiment_category = _classify_sentiment_category(variant["emotion_sentiment"])
    call_to_action_type = _classify_call_to_action_type(variant["call_to_action"])
    has_sports_or_entertainment = bool(variant.get("sports_or_entertainment_references"))

    # Shorter spots are modeled as cheaper to air at the same budget, so they
    # accumulate proportionally more impressions over the same flight.
    base_impressions = rng.randint(60_000, 220_000)
    impressions = round(base_impressions * (30_000 / duration_ms))

    click_through_rate = 0.012
    if sentiment_category == "Positive":
        click_through_rate += 0.006
    else:  # "Mixed" (comedic discomfort/awkwardness resolving positively)
        click_through_rate -= 0.002
    if has_sports_or_entertainment:
        click_through_rate += 0.004
    click_through_rate += rng.uniform(-0.002, 0.002)
    click_through_rate = max(0.004, click_through_rate)
    clicks = round(impressions * click_through_rate)

    conversion_rate = 0.07
    if call_to_action_type in ("GetAQuote", "PhoneCall"):
        conversion_rate += 0.02
    conversion_rate += rng.uniform(-0.01, 0.01)
    conversion_rate = max(0.02, conversion_rate)
    conversions = round(clicks * conversion_rate)

    # Simulated average first-year premium per converted quote.
    avg_policy_value = rng.uniform(650, 1350)
    revenue_usd = round(conversions * avg_policy_value, 2)

    return {
        "campaign_name": campaign_name,
        "result_id": result_id,
        "duration_ms": duration_ms,
        "impressions": impressions,
        "clicks": clicks,
        "click_through_rate": round(click_through_rate, 4),
        "conversions": conversions,
        "conversion_rate": round(conversion_rate, 4),
        "revenue_usd": revenue_usd,
        "sentiment_category": sentiment_category,
        "call_to_action_type": call_to_action_type,
        "is_simulated": True,
    }


def generate(seed: int) -> list[dict]:
    rng = random.Random(seed)
    rows: list[dict] = []
    for campaign in CAMPAIGNS:
        for variant_index, variant in enumerate(campaign.variants):
            rows.append(_simulate_row(rng, campaign.campaign_name, variant_index, variant))
    return rows


def write_csv(rows: list[dict], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDNAMES)
        writer.writeheader()
        writer.writerows(rows)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for simulated impressions/clicks/conversions (deterministic by default).",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    rows = generate(args.seed)
    write_csv(rows, args.output)
    print(f"Wrote {len(rows)} simulated campaign sales row(s) to {args.output}")


if __name__ == "__main__":
    main()
